[package]
name = "crescent"
version = "0.1.0"
edition = "2021"
exclude = [".github", "tests"]
categories = ["command-line-utilities"]
description = "A process manager for game servers or services."
keywords = ["process-manager", "minecraft", "socket", "tui"]
repository = "https://github.com/Kyagara/crescent"
homepage = "https://github.com/Kyagara/crescent"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.7", features = ["derive"] }
crossbeam = "0.8.2"
crossterm = "0.26.1"
daemonize = "0.5.0"
log = "0.4.17"
notify = "5.1.0"
tui = { version = "0.20.1", package = "ratatui" }
subprocess = "0.2.9"
sysinfo = "0.28.4"
tabled = "0.11.1"
tui-input = "0.7.0"
tui-logger = { version = "0.9.1", features = ["ratatui-support"], default-features = false }

[dev-dependencies]
assert_cmd = "2.0.11"

[profile.release]
strip = true
lto = true
codegen-units = 1

[[bin]]
name = "cres"
path = "src/main.rs"
