[package]
name = "crescent-cli"
version = "0.4.2"
edition = "2021"
exclude = [".github", "tests", "tools"]
categories = ["command-line-utilities"]
description = "🌙 process manager for game servers and services."
keywords = ["process-manager", "minecraft", "socket", "tui"]
repository = "https://github.com/Kyagara/crescent"
homepage = "https://github.com/Kyagara/crescent"
license = "Apache-2.0"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["test_utils"]

[workspace.dependencies]
anyhow = "1.0.70"
serial_test = "2.0.0"
predicates = "3.0.3"
assert_cmd = "2.0.11"

[dependencies]
anyhow.workspace = true
clap = { version = "4.3.3", features = ["derive"] }
crossbeam = "0.8.2"
crossterm = { version = "0.26.1", default-features = false }
daemonize = "0.5.0"
log = "0.4.19"
notify = "5.2.0"
tui = { version = "0.21.0", package = "ratatui" }
subprocess = "0.2.9"
sysinfo = "0.28.4"
tabled = { version = "0.12.2", features = ["derive"], default-features = false }
tui-input = "0.7.1"
tui-logger = { version = "0.9.2", features = ["ratatui-support"], default-features = false }
chrono = { version = "0.4.26", default-features = false }
libc = { version = "0.2.146" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"

[dev-dependencies]
anyhow.workspace = true
serial_test.workspace = true
predicates.workspace = true
test_utils = { path = "test_utils" }

[profile.release]
strip = true
lto = true
codegen-units = 1

[[bin]]
name = "cres"
path = "src/main.rs"
