[package]
name = "crescent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive"] }
crossbeam = "0.8.2"
daemonize = "0.5.0"
notify = "5.1.0"
subprocess = "0.2.9"
sysinfo = "0.28.4"
tabled = "0.11.1"
