[package]
name = "crescent-cli"
version = "0.3.1"
edition = "2021"
exclude = [".github", "tests", "tools"]
categories = ["command-line-utilities"]
description = "A process manager for game servers or services."
keywords = ["process-manager", "minecraft", "socket", "tui"]
repository = "https://github.com/Kyagara/crescent"
homepage = "https://github.com/Kyagara/crescent"
license = "MIT"
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.7", features = ["derive"] }
crossbeam = "0.8.2"
crossterm = { version = "0.26.1", default-features = false }
daemonize = "0.5.0"
log = "0.4.17"
notify = "5.1.0"
tui = { version = "0.20.1", package = "ratatui" }
subprocess = "0.2.9"
sysinfo = "0.28.4"
tabled = { version = "0.12.0", features = ["derive"], default-features = false }
tui-input = "0.7.0"
tui-logger = { version = "0.9.1", features = ["ratatui-support"], default-features = false }
chrono = { version = "0.4.24", default-features = false }
libc = { version = "0.2.144", default-features = false }
serde = { version = "1.0.163", features = ["derive"], default-features = false }
serde_json = "1.0.96"

[build-dependencies]
anyhow = "1.0.70"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "2.1.5"
serial_test = "2.0.0"

[profile.release]
strip = true
lto = true
codegen-units = 1

[[bin]]
name = "cres"
path = "src/main.rs"
