name: Continuous integration

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ./target
                  key: test-cargo-registry

            - name: Clippy
              run: cargo clippy

            - name: Format
              run: cargo fmt --check

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ./target
                  key: test-cargo-registry

            - name: Run tests
              run: cargo test

            - name: Run list command tests
              run: cargo test list_command_ -- --include-ignored --test-threads=1

    coverage:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ./target
                  key: test-cargo-registry

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Generate code coverage
              run: cargo llvm-cov --lcov --output-path lcov.info -- --include-ignored

            - name: Upload to codecov.io
              uses: codecov/codecov-action@v3
              with:
                  files: lcov.info
                  fail_ci_if_error: true

    # https://github.com/nicolas-van/rust-cross-compile-example/
    build:
        needs: test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                target:
                    [
                        x86_64-unknown-linux-gnu,
                        x86_64-unknown-linux-musl,
                        aarch64-unknown-linux-gnu,
                        aarch64-unknown-linux-musl,
                        armv7-unknown-linux-gnueabihf,
                        armv7-unknown-linux-musleabihf,
                        arm-unknown-linux-gnueabihf,
                        arm-unknown-linux-musleabihf,
                    ]
        env:
            TARGET: ${{ matrix.target }}
        steps:
            - uses: actions/checkout@v3

            - name: Cargo cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ./target
                  key: build-cargo-registry-${{matrix.target}}

            - name: List
              run: find ./

            - name: Install and configure dependencies
              run: |
                  sudo apt-get install -qq crossbuild-essential-arm64 crossbuild-essential-armhf

                  cat >>~/.cargo/config <<EOF
                  [target.aarch64-unknown-linux-gnu]
                  linker = "aarch64-linux-gnu-gcc"
                  [target.aarch64-unknown-linux-musl]
                  linker = "aarch64-linux-gnu-gcc"
                  [target.armv7-unknown-linux-gnueabihf]
                  linker = "arm-linux-gnueabihf-gcc"
                  [target.armv7-unknown-linux-musleabihf]
                  linker = "arm-linux-gnueabihf-gcc"
                  [target.arm-unknown-linux-gnueabihf]
                  linker = "arm-linux-gnueabihf-gcc"
                  [target.arm-unknown-linux-musleabihf]
                  linker = "arm-linux-gnueabihf-gcc"
                  EOF

            - name: Install rust target
              run: rustup target add $TARGET

            - name: Build
              run: cargo build --release --target $TARGET

            - name: List target
              run: find ./target

            - name: Compress
              run: |
                  mkdir -p ./artifacts
                  mv ./target/$TARGET/release/cres ./cres
                  tar -czf ./artifacts/cres-$TARGET.tar.gz cres

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: cres-$TARGET.tar.gz
                  path: ./artifacts/cres-$TARGET.tar.gz
