name: Continuous integration

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: -Dwarnings

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: Swatinem/rust-cache@v2

            - name: Build
              run: cargo build

            - name: Unit tests
              run: cargo test unit_

            - name: Test no apps running
              run: cargo test _no_apps_running

            - name: Test commands
              run: cargo test _command

            - name: Test long running service
              run: cargo test _long_running_service

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: Swatinem/rust-cache@v2

            - name: Clippy
              run: cargo clippy

            - name: Format
              run: cargo fmt --check

    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: Swatinem/rust-cache@v2

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Generate code coverage
              run: cargo llvm-cov --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@v3
              with:
                  files: lcov.info
                  fail_ci_if_error: true
